# Generated by Django 5.1.15 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('nova_poshta', 'Нова пошта'), ('courier', 'Кур’єрська доставка'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою'), ('cod', 'Післяплата'), ('online', 'Онлайн-оплата')], default='card', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('paid', 'Оплачено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('completed', 'Виконане'), ('cancelled', 'Скасоване')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
