# Generated by Django 5.1.15 on 2026-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_delivery_method_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дані платежу'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider_order_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID платежу в провайдері'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Не потрібна'), ('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Не вдалося оплатити'), ('cancelled', 'Скасовано')], default='not_required', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID транзакції'),
        ),
    ]
