# Generated by Django 5.1.15 on 2026-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_payment_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='gallery',
            field=models.JSONField(blank=True, default=list, verbose_name='Галерея'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_base',
            field=models.CharField(blank=True, max_length=255, verbose_name='Базові ноти'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_middle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Середні ноти'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_top',
            field=models.CharField(blank=True, max_length=255, verbose_name='Топ-ноти'),
        ),
    ]
