# Generated by Django 5.1.15 on 2026-10-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_create_variants_for_existing_perfumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='perfumes/', verbose_name='Зображення'),
        ),
    ]
